name    'elasticsearch-logstashforwarder'
version '0.1.0'
source 'https://github.com/elasticsearch/puppet-logstashforwarder'
author 'elasticsearch'
license 'Apache License, Version 2.0'
summary 'Module for managing and configuring logstash forwarder'
description 'Module for managing and configuring logstash forwarder'
project_page 'https://github.com/elasticsearch/puppet-logstashforwarder'
dependency 'puppetlabs/stdlib', '>= 3.0.0'

